[package]
name = "learning_vmaf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gstreamer = "0.21.0"
gstreamer-app = "0.21.0"
libvmaf-sys = "0.3.6"
os_str_bytes = "6.5.1"
